---
run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - golint

linters-settings:
  gofmt:
    simplify: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
    enable-all: true
