---
run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - dogsled
  - errcheck
  - goconst
  - gocritic
  - goimports
  - golint
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - interfacer
    # - maligned
  - misspell
  - nakedret
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck

linters-settings:
  gofmt:
    simplify: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
    enable-all: true
