---
run:
  timeout: 6m

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - dogsled
  - errcheck
  - goconst
  - gocritic
  - goimports
  - golint
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - maligned
  - misspell
  - nakedret
  # - rowserrcheck # disabled due to bug <https://github.com/golangci/golangci-lint/issues/943>
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/enosi/trade-engine
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
    enable-all: true
